# assets.yaml
parameters:
  dist.basePath: "%env(STYLESHEETPATH)%/dist"
  dist.uri: "%env(STYLESHEET_PATH_URI)%/dist"

imports:
  - { resource: "assets/_proto.yaml" }
  - { resource: "assets/css.yaml" }
  - { resource: "assets/js.yaml" }
  - { resource: "assets/app-asset.yaml" }
  - { resource: "assets/js-localize.yaml" }
