# js.yaml
services:
  scriptEnqueue.prototype:
    abstract: true
    class: 'Vigihdev\WpAssets\DTOs\ScriptEnqueueDto'
    arguments:
      $version: "%env(ASSETS_VERSION)%"

  jsOptions.prototype:
    abstract: true
    class: 'Vigihdev\WpAssets\DTOs\JsOptionsDto'

  js.footer.prototype:
    parent: "jsOptions.prototype"
    arguments:
      $inFooter: true

  js.defer.prototype:
    parent: "js.footer.prototype"
    arguments:
      $strategy: "defer"

  depends_jquery.prototype:
    parent: "scriptEnqueue.prototype"
    arguments:
      $depends: ["jquery-min"]

  # css prototype
  styleEnqueue.prototype:
    abstract: true
    class: 'Vigihdev\WpAssets\DTOs\StyleEnqueueDto'
    arguments:
      $media: "all"
      $version: "%env(ASSETS_VERSION)%"
      $depends: []
