# app-asset.yaml
services:
  app.asset:
    class: 'Vigihdev\WpAssets\DTOs\AppAssetDto'
    arguments:
      $basepath: "%dist.basePath%"
      $baseUrl: "%dist.uri%"
      $version: "%env(ASSETS_VERSION)%"
      $jsOption: "@js.defer.prototype"
      $js:
        - "js/bootstrap-bundle.js"
        - "js/themes.js"
      $css:
        - "css/offline.css"
        - "css/themes.css"

  Vigihdev\WpAssets\Contracts\Manager\AppAssetManagerInterface:
    public: true
    class: 'Vigihdev\WpAssets\Service\AppAssetManager'
    arguments:
      $asset: "@app.asset"
