services:
  bootstrap.min.css:
    parent: "styleEnqueue.prototype"
    tags: ["css"]
    arguments:
      $srcUri: "https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      $handle: "bootstrap-min-css"

  test.css:
    parent: "styleEnqueue.prototype"
    tags: ["css"]
    arguments:
      $srcUri: "%dist.uri%/css/test.css"
      $handle: "test-css"

  # Service
  Vigihdev\WpAssets\Contracts\Manager\CssManagerInterface:
    class: 'Vigihdev\WpAssets\Service\CssManager'
    public: true
    arguments:
      $assets: !tagged_iterator css
