# js-localize.yaml
services:
  localize:
    class: 'Vigihdev\WpAssets\DTOs\ScriptLocalizeDto'
    arguments:
      $handle: "nonce-js"
      $variableName: "WP_API"
      $actionPrefix: "wp_ajax_"
      $nonce: "wp_ajax_nonce"
      $depends: ["jquery-min"]
      $actions:
        - "order"
        - "btn_harga"

  Vigihdev\WpAssets\Contracts\Manager\JsLocalizerManagerInterface:
    public: true
    class: 'Vigihdev\WpAssets\Service\JsLocalizerManager'
    arguments:
      $localize: "@localize"
