# js-module.yaml
services:
  js_module.dto:
    class: 'Vigihdev\WpAssets\DTOs\JsModuleDto'
    arguments:
      $basepath: "%dist.basePath%/module-js"
      $baseUrl: "%dist.uri%/module-js"
      $version: "%env(ASSETS_VERSION)%"
      $jsOption: "@js.defer.prototype"
      $depends: ["%jquery.handle%"]
      $js:
        - "main.js"

  Vigihdev\WpAssets\Contracts\Manager\JsModuleManagerInterface:
    public: true
    class: 'Vigihdev\WpAssets\Service\JsModuleManager'
    arguments:
      $jsModule: "@js_module.dto"
