# js.yaml
services:
  jquery_slim_min.js:
    parent: "scriptEnqueue.prototype"
    tags: ["js"]
    arguments:
      $srcUri: "https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      $handle: "jquery-slim-min"
      $jsOption: "@js.defer.prototype"
      $depends: ["%jquery.handle%"]

  test.js:
    parent: "scriptEnqueue.prototype"
    tags: ["js"]
    arguments:
      $srcUri: "%dist.uri%/js/test.js"
      $handle: "test-js"
      $jsOption: "@js.defer.prototype"
      $depends: ["%jquery.handle%"]

  Vigihdev\WpAssets\Contracts\Manager\JsManagerInterface:
    class: 'Vigihdev\WpAssets\Service\JsManager'
    public: true
    arguments:
      $assets: !tagged_iterator js
